#! @bash@/bin/bash
set -e
PATH=@gawk@/bin:@zfs@/bin:@systemd@/bin:@busybox@/bin

root="$(awk '$2 == "/" { print $1 }' /proc/mounts)"

cd "$2" # early-dir
mkdir -p local-fs.target.requires
zfs list -Ho name,mountpoint | awk '$2 ~ /^\// { print $1 " " $2 }' | while read name mountpoint; do
  if [ "$name" = "$root" ]; then
    continue
  fi

  unit="$(systemd-escape -p "$mountpoint").mount"
  ln -s "../$unit" "local-fs.target.requires/$unit"
  cat > "$unit" <<EOF
# Automatically generated by systemd-zfs-generator

[Unit]
SourcePath=/dev/zfs
Documentation=man:zfs(8) man:systemd-zfs-generator(8)
Before=local-fs.target

[Mount]
What=$name
Where=$mountpoint
Type=zfs
Options=zfsutil
EOF
done
